---
deployment:
  tasks:
    - export DEPLOYPATH=/home/contacto/caja-front
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R frontend/dist/* $DEPLOYPATH
    - export APIDEPLOYPATH=/home/contacto/induwell-api
    - /bin/mkdir -p $APIDEPLOYPATH
    - /bin/cp -R backend/* $APIDEPLOYPATH
